coolie
guvanch-amangeldiyev-idf/test_project_mx pull request #15
Opened 2022-04-29 08:29 UTC by guvanch-amangeldiyev

2022-05-06 13:18 UTC, ilya-safyan-idf commented on packages/domain/lib/usecase/get_build_usecase.dart
> +                //where((element)=> element.propertyClass == "hudson.model.ParametersDefinitionProperty")
comments

2022-05-06 13:18 UTC, ilya-safyan-idf commented on packages/presentation/lib/mapper/build_mapper/build_mapper.dart
> +abstract class BuildMapper {
please change class name . 
it's not clear by the name what's going on here.

2022-05-06 13:18 UTC, ilya-safyan-idf commented on packages/domain/lib/usecase/post_usecase.dart
> +class BuildUseCase
also rename it. 
Use-case name should tell what happening here

2022-05-06 13:18 UTC, ilya-safyan-idf commented on packages/domain/lib/usecase/post_usecase.dart
> +class BuildUseCase
For ex: clearCache_usecase, getData_usecase etc

2022-05-06 13:18 UTC, ilya-safyan-idf commented on packages/presentation/lib/screen/build_screen/ui/build_sc_item.dart
> +            onTap: () {},
fill onTap action

2022-05-06 13:18 UTC, ilya-safyan-idf commented on packages/presentation/lib/screen/splash/splash.dart
> +          SvgPicture.asset("assets/svg/jenkis.svg"),
you can create constant file with SvgPicture.asset("assets/svg/jenkis.svg"). And just return svg by name.

2022-05-10 07:14 UTC, guvanch-amangeldiyev commented on packages/domain/lib/usecase/post_usecase.dart
> +class BuildUseCase
it is build screen's usecase

we call usually if is LoginScreen we named LoginUseCase

2022-05-10 07:17 UTC, guvanch-amangeldiyev commented on packages/presentation/lib/screen/splash/splash.dart
> +          SvgPicture.asset("assets/svg/jenkis.svg"),
done

2022-05-10 09:52 UTC, guvanch-amangeldiyev commented on packages/presentation/lib/mapper/build_mapper/build_mapper.dart
> +abstract class BuildMapper {
done

2022-05-10 09:52 UTC, guvanch-amangeldiyev commented on packages/domain/lib/usecase/get_build_usecase.dart
> +                //where((element)=> element.propertyClass == "hudson.model.ParametersDefinitionProperty")
done

2022-05-10 09:59 UTC, ilya-safyan-idf approved these changes

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf requested changes

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/core/api_key.dart
>    static const String login = "flutter_lab_test";
remove it

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/network_repository.dart
> +class LoginNetworkRepository extends ApiBaseRepositoryImpl
don't create the repository (LoginNetworkRepository, BuildNetworkRepository) for each screen. keep one class - NetworkRepository

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/property_repository.dart
> +class BuildNetworkRepository extends ApiBaseRepositoryImpl
-//-

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/request_impl_repository.dart
> +class RequestRepository extends ApiBaseRepositoryImpl
-//-

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/propery/api_property.dart
> +  static ApiPropertyResponse? fromJson(dynamic data) {
move it to separate mapper

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/build_screen/ui/build_sc_item.dart
> +final appNavigator = GetIt.I.get<AppNavigator>();
why do u need it here?

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/build_screen/ui/build_sc_item.dart
> +final BuildScreenMapper _mainViewMapper = GetIt.I.get<BuildScreenMapper>();
move it to the class level

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login_main.dart
>                //key: const Key("login"),
remove comment

2022-05-10 12:16 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/login_main.dart
>                //key: const Key("password"),
-//-

2022-05-10 12:26 UTC, guvanch-amangeldiyev commented on packages/data/lib/core/api_key.dart
>    static const String login = "flutter_lab_test";
done

2022-05-11 08:01 UTC, sergei-mikhailovskii-idf requested changes

2022-05-11 08:01 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/propery/api_property.dart
> +        .listConverterToMap(listParameterDefinitions);
need to refactor it. mapper should not be injected into response. mapper should be called in handling api response

2022-05-11 08:01 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/build_screen/bloc/bloc_build.dart
> +    appNavigator.popAndPush(MainPage.page());
when u go to build screen, u have the following stack

BuildScreen
MainScreen

so, if u pop the stack, u'll have MainScreen here. that's why u need pop instead of popAndPush

2022-05-11 08:01 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/build_screen/ui/build_sc_item.dart
> +        .mapPropertyText(blocData.property, bloc.onChangeValue);
move mapper initialization out of build method, to class level. but keep it's calling here

2022-05-11 15:55 UTC, sergei-mikhailovskii-idf approved these changes

2022-05-11 15:55 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/dio/dio_builder.dart
> +  //dio.interceptors.addAll(interceptors);
remove it

2022-05-12 07:34 UTC, merged